version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
  
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: employee_db
    ports:
      - "5432:5432"

  employee-service:
    build: ./employee-service
    ports:
      - "8080:8080"
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: employee_db
    depends_on:
      - postgres
      - kafka

  organization-service:
    build: ./organization-service
    ports:
      - "8081:8081"
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: organization_db
    depends_on:
      - postgres
      - kafka

  department-service:
    build: ./department-service
    ports:
      - "8082:8082"
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: department_db
    depends_on:
      - postgres
      - kafka
